name: medfinderflutter
description: Projeto Integrador 4

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-146.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.10
  geolocator: ^10.0.0
  flutter_native_splash: ^1.3.3
  flutter_launcher_icons: ^0.9.3
  image: ^3.1.0
  xml: ^5.3.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.10
  http: ^1.1.0
  provider: 6.1.1
  mask_text_input_formatter: ^2.5.0
  dio: ^4.0.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6





flutter_native_splash:
  color: "#0CB496"
  image: "assets/images/splash.png"
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  ios: true
  android: "launcher_icon"
  adaptive_icon_foreground: "assets/images/icon.png"
  min_sdk_android: 21

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mask_text_input_formatter: ^2.5.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/splashGreen.png
