name: medfinderflutter
description: Projeto Integrador 4

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-146.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.10
  geolocator: ^10.0.0
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.10
  http: ^1.1.0
  provider: 6.1.1
  mask_text_input_formatter: ^2.5.0




flutter_native_splash:
  color: "#0CB496"
  image: "assets/images/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/app/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app/icon-android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mask_text_input_formatter: ^2.5.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/splashGreen.png
